@(#)CERN job starter $Date: 2010/06/23 14:22:16 $
Working directory is </pool/lsf/ktos/773719886> on <b6e2db33b5.cern.ch>

/pool/lsf/ktos/773719886
----- Begin Fatal Exception 26-Feb-2016 13:54:57 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ggHanalyzer_RECO_cfg_ggH125a9_GenTauDecayID_IndividualRECO_minFilterObj0_FEB25.py
Exception Message:
python encountered the error: <type 'exceptions.TypeError'>
__init__() takes exactly 2 arguments (1 given)
----- End Fatal Exception -------------------------------------------------

Job finished at Fri Feb 26 13:54:57 CET 2016 on node 
 under linux version Scientific Linux CERN SLC release 6.7 (Carbon)

CERN statistics: This process used approximately : 0:00:02 KSI2K hours (2 KSI2K seconds)
                 This process corresponds to     : 0:00:08 HS06  hours (8 HS06  seconds)
